# Generated by Django 4.2.6 on 2023-10-14 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savecoin',
            old_name='dete',
            new_name='date',
        ),
    ]
